export const EventRegistryABI = [
  {
    type: 'function',
    name: 'getStatus',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'isResolved',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'isCancelled',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'candidates',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bytes32[]' }],
  },
  {
    type: 'function',
    name: 'getEventMeta',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [
      { name: 'status', type: 'uint8' },
      { name: 'lockTime', type: 'uint256' },
      { name: 'resolveTime', type: 'uint256' },
      { name: 'claimWindow', type: 'uint256' },
      { name: 'submittedAt', type: 'uint256' },
      { name: 'finalizedAt', type: 'uint256' },
      { name: 'cancelledAt', type: 'uint256' },
      { name: 'resolutionHash', type: 'bytes32' },
      { name: 'snapshotHash', type: 'bytes32' },
      { name: 'resolvedBy', type: 'address' },
    ],
  },
  {
    type: 'function',
    name: 'getEventTiming',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [
      { name: 'lockTime', type: 'uint256' },
      { name: 'resolveTime', type: 'uint256' },
      { name: 'resolutionTimeout', type: 'uint256' },
      { name: 'claimWindow', type: 'uint256' },
      { name: 'eventResolver', type: 'address' },
      { name: 'eventGovernance', type: 'address' },
    ],
  },
  {
    type: 'function',
    name: 'finalRank',
    stateMutability: 'view',
    inputs: [
      { name: 'eventId', type: 'uint256' },
      { name: 'candidateId', type: 'bytes32' },
    ],
    outputs: [{ name: '', type: 'uint16' }],
  },
  {
    type: 'function',
    name: 'claimsOpenAt',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'claimDeadline',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
] as const
