export const EventRegistryABI = [
  {
    type: 'function',
    name: 'getStatus',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'isResolved',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'isCancelled',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'candidates',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bytes32[]' }],
  },
  {
    type: 'function',
    name: 'getEventMeta',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [
      { name: 'lockTime', type: 'uint256' },
      { name: 'resolveTime', type: 'uint256' },
      { name: 'candidateCount', type: 'uint256' },
      { name: 'resolver', type: 'address' },
      { name: 'governance', type: 'address' },
    ],
  },
  {
    type: 'function',
    name: 'getEventTiming',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [
      { name: 'lockTime', type: 'uint256' },
      { name: 'resolveTime', type: 'uint256' },
      { name: 'claimsOpenAt', type: 'uint256' },
      { name: 'claimDeadline', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'finalRank',
    stateMutability: 'view',
    inputs: [
      { name: 'eventId', type: 'uint256' },
      { name: 'candidateId', type: 'bytes32' },
    ],
    outputs: [{ name: '', type: 'uint16' }],
  },
  {
    type: 'function',
    name: 'claimsOpenAt',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'claimDeadline',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
] as const
